### ISSUE TITLE
Premium for this Vanilla HTML?

### ISSUE THREAD

**Issue by arturmamedov** [justboil/admin-one-tailwind#2]
Hi, i see booth theme this one and the Vue version, and see that in Vue version there also a premium that have more features. 
And i really enjoy the premium but it hard for me to integrate a Vue version in my project, i need the vanilla HTML for work. 
Have you a possibility or i after i purchase the theme to build the vanilla one from the premium vue and use it in my Laravel & Liwewire project?

**Comment by arturmamedov** [comment]
Or how much is different the CSS of this HTML version from the Vue version. cause i want to grab this and maybe later add to it the darkmode and other features that are in the Vue version.

**Comment by vikdiesel** [comment]
Hi @arturmamedov,

Thanks for your interest. Unfortunately, there's no Premium Vanilla HTML version. But, you can reuse tailwind CSS & configs from Vue version, as well as component markup (via Inspect element in browser)

**Comment by arturmamedov** [comment]
Ok, thanks, so it have same base if i for example copy the CSS of premium and attach it on this vanilla version it work.

Sorry that i ask this here, but what i have with premium version? And how long my license work for upgrade and support?

**Comment by vikdiesel** [comment]
No, here's how it'll work:
* Copy tailwind config and CSS sources
* Copy html markup via *Inspect element* in browser
* Add action logic (for instance, when user opens navbar menu on mobile layout, or when user expands/collapses aside menu)
